# Generated by Django 3.0.8 on 2020-07-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filepool',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client id'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.FilePool', verbose_name='File Pool id'),
        ),
    ]
