# Generated by Django 3.0.8 on 2020-07-17 14:54

from django.db import migrations, models
import fs.models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_auto_20200717_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.FileField(default=0, upload_to=fs.models.file_directory_path, verbose_name='File'),
            preserve_default=False,
        ),
    ]
