# Generated by Django 3.0.8 on 2020-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_file_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.AddField(
            model_name='file',
            name='display_name',
            field=models.CharField(max_length=50, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
