# Generated by Django 3.0.8 on 2020-07-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_auto_20200717_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.FilePool', verbose_name='File Pool'),
        ),
    ]
