# Generated by Django 3.0.8 on 2020-07-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_auto_20200723_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_pool',
            new_name='filepool',
        ),
    ]
