# Generated by Django 3.0.8 on 2020-07-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fs', '0006_auto_20200723_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepool',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='filepool',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filepools', to=settings.AUTH_USER_MODEL, verbose_name='Client id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filepool',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fs.FilePool', verbose_name='File Pool'),
        ),
    ]
