# Generated by Django 3.0.8 on 2020-08-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_auto_20200727_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('filepool', 'display_name')},
        ),
    ]
