# Generated by Django 3.0.8 on 2020-08-15 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fs', '0008_auto_20200806_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filepool',
            unique_together={('owner', 'path')},
        ),
    ]
