# Generated by Django 3.0.8 on 2020-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, help_text='150 characters or fewer.', max_length=150, null=True, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='file_tree',
            field=models.TextField(blank=True, null=True, verbose_name='File Tree'),
        ),
    ]
