# Generated by Django 3.0.8 on 2020-07-27 15:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200727_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='file_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='File Tree'),
        ),
    ]
