# Generated by Django 3.0.8 on 2020-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200727_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='file_tree',
            field=models.TextField(blank=True, null=True, verbose_name='File Tree'),
        ),
    ]
