# Generated by Django 3.0.8 on 2020-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200801_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='file_tree',
            field=models.TextField(blank=True, default='{"display":"root","filepool":0,"subtrees":[]}', verbose_name='File Tree'),
        ),
    ]
