# Generated by Django 3.0.8 on 2020-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200815_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, help_text='150 characters or fewer.', max_length=150, null=True, unique=True, verbose_name='Client name'),
        ),
    ]
